const $=s=>document.querySelector(s),fmt=n=>Number(n).toLocaleString('ru-RU')+" so'm",esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TABS={dash:'📊 Dashboard',orders:'🧾 Buyurtmalar',items:'🍔 Taomlar',cats:'🗂 Kategoriyalar',set:'⚙️ Sozlamalar'},ST=['Yangi','Tayyorlanmoqda','Yetkazilmoqda','Yetkazildi','Bekor qilindi'];
let T=sessionStorage.t||'',tab='dash',D,img='',filt='';
const api=async(u,m='GET',b)=>{const r=await fetch('/api/admin'+u,{method:m,headers:{'Content-Type':'application/json',Authorization:'Bearer '+T},body:b?JSON.stringify(b):undefined});if(r.status==401){out();throw 0}const j=await r.json();if(!r.ok){alert(j.error||'Xato');throw 0}return j};
async function login(){const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('#u').value,password:$('#p').value})}),j=await r.json();if(!r.ok)return $('#le').textContent=j.error;T=sessionStorage.t=j.token;init()}
function out(){sessionStorage.t='';T='';$('#lg').style.display='block';$('#pn').style.display='none'}
function init(){if(!T)return;$('#lg').style.display='none';$('#pn').style.display='block';go(tab)}
async function go(t){tab=t;$('#nav').innerHTML=Object.entries(TABS).map(([k,v])=>`<button class="${k==t?'on':''}" onclick="go('${k}')">${v}</button>`).join('');D=await(await fetch('/api/public')).json();await V[t]()}
const c=h=>$('#c').innerHTML=h,opt=(v,l)=>`<option value="${v}">${l}</option>`;
const V={
async dash(){const s=await api('/stats');c(`<div class="st"><div>Bugungi buyurtmalar<b>${s.orders}</b></div><div>Bugungi tushum<b>${fmt(s.revenue)}</b></div><div>Sotilgan taomlar<b>${s.sold}</b></div><div>Mijozlar soni<b>${s.customers}</b></div><div>Yangi buyurtmalar<b>${s.newOrders}</b></div></div>`)},
async orders(){const L=(await api('/orders')).filter(x=>!filt||x.status==filt);c(`<select onchange="filt=this.value;V.orders()"><option value="">Barcha buyurtmalar</option>${ST.map(s=>`<option ${s==filt?'selected':''}>${s}</option>`)}</select>${L.map(x=>`<details class="box"><summary><b>#${x.id}</b> · ${esc(x.created)} · ${esc(x.phone)} · ${fmt(x.total)} · <i>${x.status}</i></summary><div class="sum">${x.items.map(i=>`<div><span>${esc(i.name)} × ${i.qty} (${fmt(i.price)})</span><b>${fmt(i.price*i.qty)}</b></div>`).join('')}<div><span>Turi</span><b>${x.type=='delivery'?'Yetkazib berish':'Olib ketish'}</b></div><div><span>Manzil</span><b>${esc(x.address)||'—'}</b></div><div><span>Izoh</span><b>${esc(x.note)||'—'}</b></div><div><span>Yetkazib berish narxi</span><b>${fmt(x.delivery)}</b></div><div><span>Umumiy</span><b>${fmt(x.total)}</b></div></div><select onchange="setSt(${x.id},this.value)">${ST.map(s=>`<option ${s==x.status?'selected':''}>${s}</option>`)}</select></details>`).join('')||'<p class="empty">Buyurtma yo\'q</p>'}`)},
items(e){const cs=D.categories;c(`<form class="box" onsubmit="saveItem(event)"><input type="hidden" id="id" value="${e?e.id:''}"><div class="g2"><input id="n" placeholder="Nomi" required value="${esc(e?.name)}"><input id="pr" type="number" min="0" placeholder="Narxi" required value="${e?e.price:''}"><select id="ct">${opt('','Kategoriyasiz')}${cs.map(k=>opt(k.id,esc(k.name)))}</select></div><textarea id="ds" rows="2" placeholder="Tavsif">${esc(e?.description)}</textarea><input type="file" accept="image/*" onchange="pick(this)"><div class="ar"><label class="ck"><input type="checkbox" id="av" ${!e||e.available?'checked':''}>Mavjud</label><label class="ck"><input type="checkbox" id="ex" ${e?.extra?'checked':''}>Qo'shimcha sifatida ko'rsat</label></div><button class="btn" style="margin-top:8px">${e?'Saqlash':'Taom qo\'shish'}</button></form>${D.items.map(i=>`<div class="box ar"><img src="${esc(i.image)}" onerror="this.style.visibility='hidden'"><div class="f"><b>${esc(i.name)}</b><br>${fmt(i.price)} · ${esc(cs.find(k=>k.id==i.category_id)?.name||'—')}${i.extra?' · qo\'shimcha':''}</div><button class="btn sm g" onclick="tg(${i.id})">${i.available?'Mavjud ✓':'Mavjud emas'}</button><button class="btn sm g" onclick="edit(${i.id})">Tahrir</button><button class="btn sm r" onclick="delItem(${i.id})">O'chirish</button></div>`).join('')}`);img=e?.image||'';if(e)$('#ct').value=e.category_id||''},
cats(){c(`<form class="box ar" onsubmit="addCat(event)"><input class="f" id="cn" placeholder="Yangi kategoriya" required><button class="btn">Qo'shish</button></form>${D.categories.map(k=>`<div class="box ar"><b class="f">${esc(k.name)}</b><button class="btn sm g" onclick="renCat(${k.id})">Nomini o'zgartirish</button><button class="btn sm r" onclick="delCat(${k.id})">O'chirish</button></div>`).join('')}`)},
set(){const s=D.settings,F=[['name','Restoran nomi'],['phone','Telefon'],['address','Manzil'],['hours','Ish vaqti'],['delivery','Yetkazib berish narxi'],['min','Minimal buyurtma summasi']];c(`<form class="box" onsubmit="saveSet(event)"><div class="g2">${F.map(([k,l])=>`<label>${l}<input id="s_${k}" value="${esc(s[k])}"></label>`).join('')}</div><label>Restoran haqida<textarea id="s_about" rows="3">${esc(s.about)}</textarea></label><label>Yangi admin paroli (ixtiyoriy)<input id="s_pw" type="password" autocomplete="new-password"></label><button class="btn">Saqlash</button></form>`)}};
const setSt=async(id,status)=>{await api(`/orders/${id}/status`,'PUT',{status});go('orders')};
function pick(el){const f=el.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const k=Math.min(1,800/im.width),cv=document.createElement('canvas');cv.width=im.width*k;cv.height=im.height*k;cv.getContext('2d').drawImage(im,0,0,cv.width,cv.height);img=cv.toDataURL('image/jpeg',.8)};im.src=r.result};r.readAsDataURL(f)}
async function saveItem(e){e.preventDefault();const id=$('#id').value,b={name:$('#n').value,price:$('#pr').value,category_id:$('#ct').value,description:$('#ds').value,image:img,available:$('#av').checked,extra:$('#ex').checked};await api(id?'/items/'+id:'/items',id?'PUT':'POST',b);go('items')}
const edit=id=>{V.items(D.items.find(i=>i.id==id));scrollTo(0,0)},tg=async id=>{const i=D.items.find(x=>x.id==id);await api('/items/'+id,'PUT',{...i,available:!i.available});go('items')},delItem=async id=>{if(confirm('Taom o\'chirilsinmi?')){await api('/items/'+id,'DELETE');go('items')}};
const addCat=async e=>{e.preventDefault();await api('/categories','POST',{name:$('#cn').value});go('cats')},renCat=async id=>{const n=prompt('Yangi nom:');if(n){await api('/categories/'+id,'PUT',{name:n});go('cats')}},delCat=async id=>{if(confirm('Kategoriya o\'chirilsinmi? (taomlar qoladi)')){await api('/categories/'+id,'DELETE');go('cats')}};
async function saveSet(e){e.preventDefault();const b={about:$('#s_about').value,password:$('#s_pw').value};['name','phone','address','hours','delivery','min'].forEach(k=>b[k]=$('#s_'+k).value);await api('/settings','PUT',b);alert('Saqlandi');go('set')}
$('#p').addEventListener('keydown',e=>e.key=='Enter'&&login());init();
