const $=s=>document.querySelector(s),fmt=n=>Number(n).toLocaleString('ru-RU')+" so'm",esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const PH="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 4 3'%3E%3Crect width='4' height='3' fill='%23ddd'/%3E%3C/svg%3E";
const ls=(k,d)=>{try{return JSON.parse(localStorage[k])||d}catch{return d}};
let D={settings:{},categories:[],items:[]},cat=0,favOnly=false,cart=ls('cart',{}),fav=ls('fav',[]),o={};
const save=()=>{localStorage.cart=JSON.stringify(cart);localStorage.fav=JSON.stringify(fav)};
const toast=m=>{const t=$('#toast');t.textContent=m;t.className='on';setTimeout(()=>t.className='',1800)};
const item=id=>D.items.find(i=>i.id==id),lines=()=>Object.entries(cart).map(([id,q])=>({i:item(id),q})).filter(x=>x.i&&x.i.available);
const sub=()=>lines().reduce((s,x)=>s+x.i.price*x.q,0),min=()=>+D.settings.min||0,dlv=()=>+D.settings.delivery||0;
async function load(){D=await(await fetch('/api/public')).json();Object.keys(cart).forEach(id=>{const i=item(id);if(!i||!i.available)delete cart[id]});save();render()}
function render(){const s=D.settings;document.title=s.name;$('#rName').textContent=$('#hName').textContent=s.name;$('#rAbout').textContent=s.about;
$('#foot').innerHTML=`<b>${esc(s.name)}</b><br>📞 ${esc(s.phone)}<br>📍 ${esc(s.address)}<br>🕒 ${esc(s.hours)}<br>Yetkazib berish: ${fmt(s.delivery)} · Minimal buyurtma: ${fmt(s.min)}`;
$('#cats').innerHTML=[{id:0,name:'Hammasi'},...D.categories].map(c=>`<button class="${!favOnly&&cat==c.id?'on':''}" onclick="setCat(${c.id})">${esc(c.name)}</button>`).join('');
const q=$('#q').value.trim().toLowerCase(),l=D.items.filter(i=>(favOnly?fav.includes(i.id):!cat||i.category_id==cat)&&i.name.toLowerCase().includes(q));
$('#grid').innerHTML=l.length?l.map(card).join(''):`<div class="empty" style="grid-column:1/-1"><span>🍽️</span>${favOnly?'Sevimlilar bo\'sh':'Hech narsa topilmadi'}</div>`;
$('#cCount').textContent=Object.values(cart).reduce((a,b)=>a+b,0);if($('#cart').classList.contains('on'))drawCart()}
const card=i=>`<div class="card"><div class="im"><img src="${esc(i.image)||PH}" onerror="this.src=PH" loading="lazy"><button class="heart ${fav.includes(i.id)?'on':''}" onclick="tf(${i.id})">♥</button></div><div class="cb"><h3>${esc(i.name)}</h3><p>${esc(i.description)}</p><div class="row"><b>${fmt(i.price)}</b>${i.available?`<button class="btn sm" onclick="add(${i.id})">Savatga qo'shish</button>`:'<span class="na">Hozircha mavjud emas</span>'}</div></div></div>`;
const setCat=id=>{cat=id;favOnly=false;render()},tf=id=>{fav=fav.includes(id)?fav.filter(x=>x!=id):[...fav,id];save();render()};
$('#favBtn').onclick=()=>{favOnly=!favOnly;render();$('#menu').scrollIntoView()};$('#q').oninput=render;
$('#theme').onclick=()=>{const d=document.documentElement.dataset.t!=='dark';document.documentElement.dataset.t=d?'dark':'';localStorage.theme=d?'dark':'';$('#theme').textContent=d?'☀️':'🌙'};
if(localStorage.theme){document.documentElement.dataset.t='dark';$('#theme').textContent='☀️'}
function add(id){if(!item(id)?.available)return;cart[id]=(cart[id]||0)+1;save();render();toast('Savatga qo\'shildi')}
function chg(id,d){cart[id]=(cart[id]||0)+d;if(cart[id]<=0)delete cart[id];save();render();if(o.step==2)step2()}
function del(id){delete cart[id];save();render()}
const ov=on=>$('#ov').classList.toggle('on',on);
$('#cartBtn').onclick=()=>{drawCart();$('#cart').classList.add('on');ov(true)};$('#ov').onclick=()=>{$('#cart').classList.remove('on');ov(false)};
function drawCart(){const L=lines(),s=sub();$('#cart').innerHTML=`<h2>🛒 Savat <button class="x" style="float:right;font-size:1.3rem" onclick="$('#ov').click()">✕</button></h2><div class="dl">${L.length?L.map(x=>`<div class="ci"><img src="${esc(x.i.image)||PH}" onerror="this.src=PH"><div><b>${esc(x.i.name)}</b><br>${fmt(x.i.price)}<div class="q"><button onclick="chg(${x.i.id},-1)">−</button><b>${x.q}</b><button onclick="chg(${x.i.id},1)">+</button></div></div><b>${fmt(x.i.price*x.q)}</b><button class="x" onclick="del(${x.i.id})">🗑</button></div>`).join(''):'<div class="empty"><span>🛒</span>Savat hozircha bo\'sh</div>'}</div>
${L.length?`<div class="tot"><div><span>Mahsulotlar jami</span><b>${fmt(s)}</b></div><div><span>Yetkazib berish</span><b>${fmt(dlv())}</b></div><div><span>Umumiy summa</span><b>${fmt(s+dlv())}</b></div>${s<min()?`<p class="err">Minimal buyurtma: ${fmt(min())}</p>`:''}<small style="color:var(--mu)">Olib ketishda yetkazib berish narxi olinmaydi</small><button class="btn" style="width:100%;margin-top:10px" ${s<min()?'disabled':''} onclick="startOrder()">Buyurtma berish</button></div>`:''}`}
const M=h=>{$('#modal').innerHTML=`<div class="mb">${h}</div>`;$('#modal').classList.add('on');ov(true)},closeM=()=>{$('#modal').classList.remove('on');ov(false);$('#cart').classList.remove('on')};
const phoneOk=v=>{let d=v.replace(/\D/g,'');if(d.length==9)d='998'+d;return/^998\d{9}$/.test(d)?'+'+d:null};
function startOrder(){o={step:1,phone:'',type:'delivery',address:'',note:''};$('#cart').classList.remove('on');step1()}
function step1(){o.step=1;M(`<h2>📱 Telefon raqamingiz</h2><input id="ph" type="tel" placeholder="+998 90 123 45 67" value="${esc(o.phone)}"><div class="err" id="e"></div><div class="acts"><button class="btn g" onclick="closeM()">Bekor</button><button class="btn" onclick="n1()">Keyingi</button></div>`)}
function n1(){const p=phoneOk($('#ph').value);if(!p)return $('#e').textContent='Telefon raqami noto\'g\'ri. Masalan: +998 90 123 45 67';o.phone=p;step2()}
function step2(){o.step=2;const ex=D.items.filter(i=>i.extra&&i.available);M(`<h2>Buyurtmangizga yana nima qo'shamiz?</h2>${ex.length?ex.map(i=>`<div class="ci"><img src="${esc(i.image)||PH}" onerror="this.src=PH"><div><b>${esc(i.name)}</b><br>${fmt(i.price)}</div><div class="q"><button onclick="chg(${i.id},-1)">−</button><b>${cart[i.id]||0}</b><button onclick="chg(${i.id},1)">+</button></div></div>`).join(''):'<p class="empty">Qo\'shimcha mahsulot yo\'q</p>'}<div class="acts"><button class="btn g" onclick="step1()">Orqaga</button><button class="btn" onclick="step3()">Keyingi</button></div>`)}
function step3(){o.step=3;M(`<h2>🚚 Qanday olasiz?</h2><label class="opt ${o.type=='delivery'?'on':''}"><input type="radio" name="t" value="delivery" ${o.type=='delivery'?'checked':''} onchange="sT(this.value)">Yetkazib berish (${fmt(dlv())})</label><label class="opt ${o.type=='pickup'?'on':''}"><input type="radio" name="t" value="pickup" ${o.type=='pickup'?'checked':''} onchange="sT(this.value)">Restorandan olib ketish</label>
<textarea id="ad" rows="2" placeholder="Yetkazib berish manzili" style="display:${o.type=='delivery'?'block':'none'}">${esc(o.address)}</textarea><textarea id="nt" rows="2" placeholder="Izoh (masalan: piyoz qo'shilmasin)">${esc(o.note)}</textarea><div class="err" id="e"></div><div class="acts"><button class="btn g" onclick="rd();step2()">Orqaga</button><button class="btn" onclick="n3()">Keyingi</button></div>`)}
function rd(){o.address=$('#ad').value.trim();o.note=$('#nt').value.trim()}
function sT(v){rd();o.type=v;step3()}
function n3(){rd();if(o.type=='delivery'&&!o.address)return $('#e').textContent='Manzilni kiriting';step4()}
function step4(){o.step=4;const s=sub(),d=o.type=='delivery'?dlv():0,L=lines();M(`<h2>✅ Buyurtmani tekshiring</h2><div class="sum">${L.map(x=>`<div><span>${esc(x.i.name)} × ${x.q} (${fmt(x.i.price)})</span><b>${fmt(x.i.price*x.q)}</b></div>`).join('')}<hr><div><span>Telefon</span><b>${esc(o.phone)}</b></div><div><span>Turi</span><b>${o.type=='delivery'?'Yetkazib berish':'Olib ketish'}</b></div>${o.type=='delivery'?`<div><span>Manzil</span><b>${esc(o.address)}</b></div>`:''}${o.note?`<div><span>Izoh</span><b>${esc(o.note)}</b></div>`:''}<div><span>Mahsulotlar</span><b>${fmt(s)}</b></div><div><span>Yetkazib berish</span><b>${fmt(d)}</b></div><div style="font-size:1.15rem"><span>Umumiy summa</span><b>${fmt(s+d)}</b></div></div><div class="err" id="e">${s<min()?'Minimal buyurtma: '+fmt(min()):''}</div><div class="acts"><button class="btn g" onclick="step3()">Orqaga</button><button class="btn" id="cf" onclick="confirmOrder()" ${!L.length||s<min()?'disabled':''}>Buyurtmani tasdiqlash</button></div>`)}
async function confirmOrder(){$('#cf').disabled=true;try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:o.phone,type:o.type,address:o.address,note:o.note,items:lines().map(x=>({id:x.i.id,qty:x.q}))})}),j=await r.json();
if(!r.ok){$('#e').textContent=j.error;$('#cf').disabled=false;return}cart={};save();render();M(`<div class="ok"><span>🎉</span><h2>Buyurtmangiz #${j.id} qabul qilindi.</h2><p>Jami: <b>${fmt(j.total)}</b><br>Tez orada siz bilan bog'lanamiz.</p><button class="btn" style="margin-top:14px" onclick="closeM()">Yopish</button></div>`)}catch{$('#e').textContent='Server bilan aloqa yo\'q';$('#cf').disabled=false}}
load();
